# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
simcpp <- function(dt, l, mc) {
    invisible(.Call('_IMPACTaf_simcpp', PACKAGE = 'IMPACTaf', dt, l, mc))
}

#' @export
carry_forward <- function(x, pid_mrk, y, byref) {
    .Call('_IMPACTaf_carry_forward', PACKAGE = 'IMPACTaf', x, pid_mrk, y, byref)
}

#' @export
carry_forward_incr <- function(x, pid_mrk, recur, y, byref) {
    .Call('_IMPACTaf_carry_forward_incr', PACKAGE = 'IMPACTaf', x, pid_mrk, recur, y, byref)
}

#' @export
carry_backward <- function(x, pid_mrk, y) {
    .Call('_IMPACTaf_carry_backward', PACKAGE = 'IMPACTaf', x, pid_mrk, y)
}

#' @export
carry_backward_decr <- function(x, pid_mrk) {
    .Call('_IMPACTaf_carry_backward_decr', PACKAGE = 'IMPACTaf', x, pid_mrk)
}

#' @export
mk_new_simulant_markers <- function(pid) {
    .Call('_IMPACTaf_mk_new_simulant_markers', PACKAGE = 'IMPACTaf', pid)
}

#' @export
identify_longdead <- function(x, pid) {
    .Call('_IMPACTaf_identify_longdead', PACKAGE = 'IMPACTaf', x, pid)
}

#' @export
identify_invitees <- function(elig, prev_inv, prb, freq, pid) {
    .Call('_IMPACTaf_identify_invitees', PACKAGE = 'IMPACTaf', elig, prev_inv, prb, freq, pid)
}

#' @export
hc_effect <- function(x, prb_of_continuation, pid) {
    .Call('_IMPACTaf_hc_effect', PACKAGE = 'IMPACTaf', x, prb_of_continuation, pid)
}

#' @export
fbound <- function(x, a, b) {
    .Call('_IMPACTaf_fbound', PACKAGE = 'IMPACTaf', x, a, b)
}

#' @export
antilogit <- function(x) {
    .Call('_IMPACTaf_antilogit', PACKAGE = 'IMPACTaf', x)
}

dtsubset <- function(x, rows, cols) {
    .Call('_IMPACTaf_dtsubset', PACKAGE = 'IMPACTaf', x, rows, cols)
}

#' @export
fscramble_trajectories <- function(x, pid, jumpiness = 1.0, inplace = TRUE) {
    .Call('_IMPACTaf_fscramble_trajectories', PACKAGE = 'IMPACTaf', x, pid, jumpiness, inplace)
}

#' @export
shift_bypidNum <- function(x, lag, replace, id) {
    .Call('_IMPACTaf_shift_bypidNum', PACKAGE = 'IMPACTaf', x, lag, replace, id)
}

#' @export
shift_bypidInt <- function(x, lag, replace, id) {
    .Call('_IMPACTaf_shift_bypidInt', PACKAGE = 'IMPACTaf', x, lag, replace, id)
}

#' @export
shift_bypidBool <- function(x, lag, replace, id) {
    .Call('_IMPACTaf_shift_bypidBool', PACKAGE = 'IMPACTaf', x, lag, replace, id)
}

#' @export
shift_bypidStr <- function(x, lag, replace, id) {
    .Call('_IMPACTaf_shift_bypidStr', PACKAGE = 'IMPACTaf', x, lag, replace, id)
}

